import React from 'react'
import Head from 'next/head'
import Header from '../../components/Header'
import Footer from '../../components/Footer'

const Pokemon = () => {
  return (
    <div>
      <Head>
        <title>My Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div>
        pokemon
      </div>
      <Footer />
    </div>
  )
}

export default Pokemon