import React from 'react'
import Head from 'next/head'
import Header from '../../components/Header'
import Footer from '../../components/Footer'
import { GetServerSideProps } from 'next'
import { useApi } from '../../libs/useApi'
import style from './style.module.scss'
import Image from 'next/image'

const Pokemon = (data: any) => {
  const pokemonName = data.getPokemon.name.charAt(0).toUpperCase() + data.getPokemon.name.slice(1);

  console.log(data.getPokemon)
  return (
    <div className={style.pokemonPageContainer}>
      <Head>
        <title>My Pokemon - {pokemonName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={style.mainContent}>
        <div className={style.imageContainer}>
          {/* <Image src={}/>{} */}
        </div>
        <div className={style.infoContainer}>

        </div>
      </main>
      <Footer />
    </div>
  )
}

export default Pokemon

type Props = {
  AllPokemons: any
  parseJson: any
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { pokemon } = context.query
  const api = useApi()
  const getPokemon = await api.getSpecificPokemon(`https://pokeapi.co/api/v2/pokemon/${pokemon}`)

  return {
    props: {
      getPokemon
    }
  }
}